### ISSUE TITLE
ReferenceError: error is not defined

### ISSUE THREAD

**Issue by MicPie21** [grzegorz914/homebridge-xbox-tv#11]
Hello, 

Since a few days. I have these errors : 

`ReferenceError: error is not defined
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:188:40)
    at EventEmitter.emit (events.js:322:22)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
    at EventEmitter.emit (events.js:310:20)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:264:30)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)`

Can you help me to solve this ? 

Thank you,

**Comment by grzegorz914** [comment]
Please get Your config.json

**Comment by MicPie21** [comment]
{
            "devices": [
                {
                    "name": "XBOXONE",
                    "host": "192.168.1.17",
                    "xboxliveid": "FD0079C6DE551A3E",
                    "switchInfoMenu": false,
                    "apps": [
                        {
                            "name": "Spotify",
                            "reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App"
                        }
                    ]
                }
            ],
            "platform": "XboxTv"
        }

**Comment by grzegorz914** [comment]
Please add rest of reference as in example and check again:

```json
{
    "platform": "XboxTv",
    "devices": [
        {
            "name": "Xbox One",
            "host": "192.168.1.6",
            "xboxliveid": "FD0000000000",
            "switchInfoMenu": true,
            "apps": [
                {
                    "name": "TV",
                    "reference": "Microsoft.Xbox.LiveTV_8wekyb3d8bbwe!Microsoft.Xbox.LiveTV.Application"
                },
                {
                    "name": "Dashboard",
                    "reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application"
                },
                {
                    "name": "Spotify",
                    "reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App"
                },
                {
                    "name": "Youtube",
                    "reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App"
                },
                {
                    "name": "Netflix",
                    "reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App"
                },
                {
                    "name": "Airserver",
                    "reference": "F3F176BD.53203526D8F6C_p8qzvses5c8me!AirServer"
                }
            ]
        }
    ]
}

**Comment by MicPie21** [comment]
I added rest of reference but the errors are still here. 
My homebridge restart every 15sec

`[4/15/2020, 20:08:28] ReferenceError: error is not defined
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:188:40)
    at EventEmitter.emit (events.js:322:22)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
    at EventEmitter.emit (events.js:310:20)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:264:30)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
[4/15/2020, 20:08:28] Got SIGTERM, shutting down Homebridge...`

**Comment by grzegorz914** [comment]
Sorry, but I see first time this error, please run Homebridge in debug mode -D and get the log.

**Comment by unknownskl** [comment]
This error looks related to this issue: https://github.com/OpenXbox/xbox-smartglass-core-node/issues/26
Problem should be fixed in the new version of the library.
