### ISSUE TITLE
Homebridge crashing on start

### ISSUE THREAD

**Issue by royaldunlin** [grzegorz914/homebridge-xbox-tv#136]
Installed this plugin today (v2.1.1) and it's causing homebridge (v.1.4.0) to crash.  I'm sure I'm missing something, but here is the log entry and the config.

```
Jan 21 18:59:00 homebridge homebridge[10587]: [1/21/2022, 6:59:00 PM] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array
Jan 21 18:59:00 homebridge homebridge[10587]:     at Object.writeFileSync (node:fs:2146:5)
Jan 21 18:59:00 homebridge homebridge[10587]:     at new xboxTvDevice (/usr/lib/node_modules/homebridge-xbox-tv/index.js:291:7)
Jan 21 18:59:00 homebridge homebridge[10587]:     at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/index.js:173:6)
Jan 21 18:59:00 homebridge homebridge[10587]:     at HomebridgeAPI.emit (node:events:402:35)
Jan 21 18:59:00 homebridge homebridge[10587]:     at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:275:10)
Jan 21 18:59:00 homebridge homebridge[10587]:     at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:173:14)
Jan 21 18:59:00 homebridge homebridge[10587]: [1/21/2022, 6:59:00 PM] Got SIGTERM, shutting down Homebridge...
```

```
"name": "Xbox One X",
"host": "172.29.7.9",
"xboxLiveId": "XXX",
"xboxWebApiToken": "XXX",
"disableLogInfo": false,
"disableLogDeviceInfo": false,
"enableDebugMode": true,
"webApiControl": true,
"volumeControl": 0,
"switchInfoMenu": false,
"getInputsFromDevice": false,
"filterGames": false,
"filterApps": false,
"filterSystemApps": false,
"filterDlc": false
```

**Comment by bslatyer** [comment]
I'm having the same issue as well
