### ISSUE TITLE
XBox No Longer Launching App (Specified Input)

### ISSUE THREAD

**Issue by shanemcw** [grzegorz914/homebridge-xbox-tv#151]
homebridge-xbox-tv v2.4.5

On running a scene in Apple Home turning the Xbox on and setting an input (i.e. launching a game), it used to function in previous versions of homebridge-xbox-tv, but as of a few subversions now, the Xbox turns on but the game (input) is not launched.

At that moment, the log states

[1/26/2023, 1:22:52 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, get Power state successful: OFF
[1/26/2023, 1:23:49 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, Send power On.
[1/26/2023, 1:23:50 PM] [homebridge-xbox-tv] **Device: 192.168.1.40 XBOX, set Input error: [object Object]**
[1/26/2023, 1:23:50 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, set Power successful: ON
[1/26/2023, 1:23:52 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, Connected.

### Second (related?) Issue
When indicating what published inputs should be shown in Apple Home during the Xbox device's setup in Apple home (long list of checkboxes) the inputs that are unchecked no longer are hidden in the UI in Home for the Xbox (e.g. when setting a scene to run a game—it now shows all and not the few that were checked in the Home settings of the Xbox)

**Comment by grzegorz914** [comment]
Same as #150

**Comment by shanemcw** [comment]
Thanks! I reviewed #150 

Via XBox settings I ran `Network settings / Test remote play` with the passing message "You are good to go" and "remote play should work"

Rebooted

On running two scenes in Home that turn on the Xbox and launch an input I logged

[1/26/2023, 2:08:42 PM] [webostv] [LG TV] Starting TV alive polling
[1/26/2023, 2:08:55 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, Send power On.
[1/26/2023, 2:08:55 PM] [homebridge-xbox-tv] **Device: 192.168.1.40 XBOX, set Input error: [object Object]**
[1/26/2023, 2:08:55 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, set Power successful: ON
[1/26/2023, 2:08:58 PM] [webostv] [LG TV] Connected to TV
[1/26/2023, 2:08:58 PM] [webostv] [LG TV] Got TV information
[1/26/2023, 2:08:58 PM] [webostv] [LG TV] TV webOS version: 5.0
[1/26/2023, 2:08:58 PM] [webostv] [LG TV] App launched, current appId: com.webos.app.hdmi2
[1/26/2023, 2:08:58 PM] [webostv] [LG TV] Sound output changed. Current sound output: tv_speaker
[1/26/2023, 2:08:59 PM] [webostv] [LG TV] TV turned on!
[1/26/2023, 2:09:00 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, Connected.
[1/26/2023, 2:09:00 PM] [homebridge-xbox-tv] -------- XBOX --------
[1/26/2023, 2:09:00 PM] [homebridge-xbox-tv] Manufacturer: Microsoft
[1/26/2023, 2:09:00 PM] [homebridge-xbox-tv] Model: Xbox One
[1/26/2023, 2:09:00 PM] [homebridge-xbox-tv] Serialnr: FD002F66DB0915E0
[1/26/2023, 2:09:00 PM] [homebridge-xbox-tv] Firmware: 10.0.22621
[1/26/2023, 2:09:00 PM] [homebridge-xbox-tv] ----------------------------------
[1/26/2023, 2:09:08 PM] [webostv] [LG TV] Subscribed to TV services
[1/26/2023, 2:09:08 PM] [webostv] [LG TV] Connected to remote pointer input socket
[1/26/2023, 2:09:08 PM] [webostv] [LG TV] Setup finished
[1/26/2023, 2:09:08 PM] [webostv] [LG TV] TV setup finished, ready to control tv
[1/26/2023, 2:09:13 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, set Power successful: ON
[1/26/2023, 2:09:13 PM] [homebridge-xbox-tv] **Device: 192.168.1.40 XBOX, set Input error: [object Object]**
[1/26/2023, 2:09:16 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, Disconnected.
[1/26/2023, 2:09:20 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, Connected.
[1/26/2023, 2:09:20 PM] [homebridge-xbox-tv] -------- XBOX --------
[1/26/2023, 2:09:20 PM] [homebridge-xbox-tv] Manufacturer: Microsoft
[1/26/2023, 2:09:20 PM] [homebridge-xbox-tv] Model: Xbox One
[1/26/2023, 2:09:20 PM] [homebridge-xbox-tv] Serialnr: FD002F66DB0915E0
[1/26/2023, 2:09:20 PM] [homebridge-xbox-tv] Firmware: 10.0.22621
[1/26/2023, 2:09:20 PM] [homebridge-xbox-tv] ----------------------------------

**Comment by shanemcw** [comment]
I think #150 may have been logged during the time before input switching stopped working for me

**Comment by grzegorz914** [comment]
Remote play have nothing to do with remote control, check Please again.

**Comment by shanemcw** [comment]
Ah Thanks—I see #150 references/is about "remote _play_"

**Comment by shanemcw** [comment]
Confirmed "remote features" and "instant on" are still active as back in the version when the input was working—confirmed "remote play" is testing as working. Is still turning the console on and off remotely correctly.

**Comment by shanemcw** [comment]
Thanks again for your thoughts! I'll revert back to a few prior versions to investigate the issue further.

**Comment by shanemcw** [comment]
some debug

[1/26/2023, 2:52:42 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Socket send Acknowledge.
[1/26/2023, 2:52:43 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 0.885 sec ago.
[1/26/2023, 2:52:44 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 1.887 sec ago.
[1/26/2023, 2:52:45 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 2.887 sec ago.
[1/26/2023, 2:52:45 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received message from: 192.168.1.40:5050
[1/26/2023, 2:52:45 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received event type: acknowledge
[1/26/2023, 2:52:45 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Packet send acknowledge.
[1/26/2023, 2:52:45 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Request number set to: 20
[1/26/2023, 2:52:45 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Socket send Acknowledge.
[1/26/2023, 2:52:46 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 0.878 sec ago.
[1/26/2023, 2:52:47 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 1.88 sec ago.
[1/26/2023, 2:52:47 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, set Power successful: ON
[1/26/2023, 2:52:47 PM] [homebridge-xbox-tv] **Device: 192.168.1.40 XBOX, set Input error: [object Object]**
[1/26/2023, 2:52:48 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 2.881 sec ago.
[1/26/2023, 2:52:48 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received message from: 192.168.1.40:5050
[1/26/2023, 2:52:48 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received event type: acknowledge
[1/26/2023, 2:52:48 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Packet send acknowledge.
[1/26/2023, 2:52:48 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Request number set to: 21
[1/26/2023, 2:52:48 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Socket send Acknowledge.
[1/26/2023, 2:52:49 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 0.87 sec ago.
[1/26/2023, 2:52:50 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 1.87 sec ago.
[1/26/2023, 2:52:50 PM] [webostv] [LG TV] Connected to TV
[1/26/2023, 2:52:51 PM] [webostv] [LG TV] Got TV information
[1/26/2023, 2:52:51 PM] [webostv] [LG TV] TV webOS version: 5.0
[1/26/2023, 2:52:51 PM] [webostv] [LG TV] App launched, current appId: com.webos.app.hdmi2
[1/26/2023, 2:52:51 PM] [webostv] [LG TV] Sound output changed. Current sound output: tv_speaker
[1/26/2023, 2:52:51 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 2.871 sec ago.
[1/26/2023, 2:52:51 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received message from: 192.168.1.40:5050
[1/26/2023, 2:52:51 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received event type: acknowledge
[1/26/2023, 2:52:51 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Packet send acknowledge.
[1/26/2023, 2:52:51 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Request number set to: 22
[1/26/2023, 2:52:51 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Socket send Acknowledge.
[1/26/2023, 2:52:51 PM] [webostv] [LG TV] TV turned on!
[1/26/2023, 2:52:52 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 0.861 sec ago.
[1/26/2023, 2:52:53 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 1.86 sec ago.
[1/26/2023, 2:52:54 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 2.861 sec ago.
[1/26/2023, 2:52:54 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received message from: 192.168.1.40:5050
[1/26/2023, 2:52:54 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received event type: acknowledge
[1/26/2023, 2:52:54 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Packet send acknowledge.
[1/26/2023, 2:52:54 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Request number set to: 23
[1/26/2023, 2:52:54 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Socket send Acknowledge.
[1/26/2023, 2:52:55 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 0.854 sec ago.
[1/26/2023, 2:52:56 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received message from: 192.168.1.40:5050
[1/26/2023, 2:52:56 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received event type: status
[1/26/2023, 2:52:56 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Status message: {
  "liveTvProvider": 0,
  "majorVersion": 10,
  "minorVersion": 0,
  "buildNumber": 22621,
  "locale": "en-US",
  "apps": [
    {
      "titleId": 1837352387,
      "flags": {
        "type": "Buffer",
        "data": [
          128,
          0
        ]
      },
      "productId": {
        "type": "Buffer",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      },
      "sandboxId": {
        "type": "Buffer",
        "data": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      },
      "aumId": "Microsoft.Xbox.Settings_8wekyb3d8bbwe!Xbox.Settings.Application"
    }
  ]
}
[1/26/2023, 2:52:56 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Status changed, app Id: 1837352387, reference: Microsoft.Xbox.Settings_8wekyb3d8bbwe!Xbox.Settings.Application
[1/26/2023, 2:52:56 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Last heart beat was: 0.033 sec ago.
[1/26/2023, 2:52:56 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received message from: 192.168.1.40:5050
[1/26/2023, 2:52:56 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, debug: Received event type: status

**Comment by grzegorz914** [comment]
can you post your Config

**Comment by shanemcw** [comment]
{
            "devices": [
                {
                    "name": "XBOX",
                    "host": "192.168.1.40",
                    "xboxLiveId": "REDACTED",
                    "clientId": "REDACTED",
                    "xboxWebApiToken": "REDACTED",
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableDebugMode": false,
                    "webApiControl": true,
                    "volumeControl": 0,
                    "getInputsFromDevice": true,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": false,
                    "sensorPower": false,
                    "sensorInput": false,
                    "sensorScreenSaver": false,
                    "enableMqtt": false,
                    "mqttAuth": false,
                    "mqttDebug": false
                }
            ],
            "_bridge": {
                "username": "0E:E7:D2:24:BA:D4",
                "port": 57008
            },
            "platform": "XboxTv"
        },

**Comment by grzegorz914** [comment]
Install 2.4.6-beta.0 and get the log

**Comment by shanemcw** [comment]
[1/26/2023, 3:42:39 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, set Input error: {
  "status": 401,
  "body": "{\r\n  \"status\": {\r\n    \"errorCode\": \"RemoteManagementDisabled\",\r\n    \"errorMessage\": \"User has disabled remote management on Xbox: FD002F66DB0915E0\"\r\n  },\r\n  \"result\": null,\r\n  \"uiText\": null,\r\n  \"destination\": null,\r\n  \"userInfo\": null\r\n}"
}

**Comment by shanemcw** [comment]
"Remote features" confirmed was/has been on; I'll toggle "Remote features" off then back on

**Comment by shanemcw** [comment]
When toggled back on, a test was automatically that reported "You are good to go". Still reporting the "RemoteManagementDisabled" in the log (although of course the console is getting remotely powered off and on correctly).

**Comment by grzegorz914** [comment]
Power console on and off have nothing to do with switch inputs, as you can read in readme to switch inputs console uses web APIs, other functions uses local api.

**Comment by shanemcw** [comment]
I cleared the web token, got a new token from the local URL via authorization manager, and set it in settings; restarted; getting
[homebridge-xbox-tv] Device: 192.168.1.40 XBOX, not authorized, please use Authorization Manager.

**Comment by shanemcw** [comment]
You mentioned switching inputs is the Web API, so I cleared the Web Token and got another and installed it.

I'm still getting 

[homebridge-xbox-tv] Device: 192.168.1.40 XBOX, not authorized, please use Authorization Manager.

but also now

It must be >= 0 and <= 12. Received 16
Error reading unsigned 32-bit integer from packet: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 12. Received 16
Error reading unsigned 32-bit integer from packet: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 12. Received 16
Error reading unsigned 32-bit integer from packet: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 12. Received 16
Error reading unsigned 32-bit integer from packet: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 12. Received 16
Error reading unsigned 32-bit integer from packet: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 12. Received 16
Error reading unsigned 32-bit integer from packet: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 12. Received 16

**Comment by shanemcw** [comment]
and now crash looping over

[1/26/2023, 4:14:11 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, not authorized, please use Authorization Manager.
Error: listen EADDRINUSE: address already in use :::57008
    at Server.setupListenHandle [as _listen2] (node:net:1733:16)
    at listenInCluster (node:net:1781:12)
    at Server.listen (node:net:1869:7)
    at EventedHTTPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:164:20)
    at HAPServer.listen (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:377:21)
    at Bridge.<anonymous> (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1365:18)
    at step (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /var/lib/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
[1/26/2023, 4:14:12 PM] [homebridge-xbox-tv] Child bridge process ended
[1/26/2023, 4:14:12 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null

**Comment by shanemcw** [comment]
Clearing the web token and re-authorizing cleared the original error of this issue thread, now, at that function, logs:

[1/26/2023, 4:23:04 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, set Input successful, input: Assassin’s Creed Rogue Remastered,, reference: ACROWW38E61E36_z1zgv8ff8e49g!scimitarlauncherF, product Id: BWT5L9P3L60X

However the game input still does not launch and I'm getting a new authorization error before that:

[1/26/2023, 4:14:11 PM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, not authorized, please use Authorization Manager.

at start of the plugin, prior to the "set Input successful, input:"

**Comment by shanemcw** [comment]
Performed the authorization and setting the web token via the Authorization Manger process a few times, all getting that same new error.

**Comment by shanemcw** [comment]
Moving the "please use Authorization Manager" error to a new issue.

**Comment by grzegorz914** [comment]
Herę is no any problem with authorization manager, trying right now on 2 consoles all working correct.

**Comment by shanemcw** [comment]
Confirmed that after resetting the web API token the issue is resolved.
