### ISSUE TITLE
Enabling a second Xbox within the plugin failing.

### ISSUE THREAD

**Issue by chris4prez** [grzegorz914/homebridge-xbox-tv#191]
I'm trying to enable a second xbox and running into issues.

1) Am I to use the same Web API Token or a new one? Running into issues with the authorization workflow to get it started cleanly in the logs. When I try to authorize for a new one, I receive the following error:
http://localhost:8888/auth/callback?error=unauthorized_client&error_description=The%20client%20does%20not%20have%20a%20secret%20configured.%20If%20you%20are%20the%20client%20application%20developer%2c%20configure%20a%20secret%20through%20the%20application%20management%20site%20at%20https://go.microsoft.com/fwlink/%3flinkid%3d2083908.

After initial adding of second xbox here is some of the errors seeing in the log:

Snippet of errors I'm seeing on adding the second one prior to above error seeing 

[03/01/2024, 17:19:21] [homebridge-xbox-tv] Launched child bridge with PID 285196
[03/01/2024, 17:19:21] Registering platform 'homebridge-xbox-tv.XboxTv'
[03/01/2024, 17:19:21] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.5 child bridge successfully
[03/01/2024, 17:19:21] Loaded 0 cached accessories from cachedAccessories.0ECF27A6D260.
[03/01/2024, 17:19:21] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 35233.
[03/01/2024, 17:19:29] Living Room Xbox Series X 0EDB is running on port 44521.
[03/01/2024, 17:19:29] Please add [Living Room Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[03/01/2024, 17:19:30] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, Power: OFF
[03/01/2024, 17:19:30] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, Input: Screensaver, Reference: Xbox.IdleScreen_8wekyb3d8bbwe!Xbox.IdleScreen.Application, Product Id: Screensaver
[03/01/2024, 17:19:30] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, Current Media: STOP
[03/01/2024, 17:19:30] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, Target Media: STOP
[03/01/2024, 17:19:30] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, Mute: ON
[03/01/2024, 17:19:30] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, Volume: 0
[03/01/2024, 17:21:33] [homebridge-xbox-tv] Restarting child bridge...
[03/01/2024, 17:21:33] Got SIGTERM, shutting down child bridge process...
[03/01/2024, 17:21:38] [homebridge-xbox-tv] Child bridge process ended
[03/01/2024, 17:21:38] [homebridge-xbox-tv] Process Ended. Code: 143, Signal: null
[03/01/2024, 17:21:45] [homebridge-xbox-tv] Restarting Process...
[03/01/2024, 17:21:46] [homebridge-xbox-tv] Launched child bridge with PID 285364
[03/01/2024, 17:21:46] Registering platform 'homebridge-xbox-tv.XboxTv'
[03/01/2024, 17:21:46] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.5 child bridge successfully
[03/01/2024, 17:21:46] Loaded 0 cached accessories from cachedAccessories.0ECF27A6D260.
[03/01/2024, 17:21:46] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 35233.
[03/01/2024, 17:21:54] Master Bedroom Xbox Series X 0EDB is running on port 32849.
[03/01/2024, 17:21:54] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[03/01/2024, 17:21:55] [homebridge-xbox-tv] Device: 10.0.1.158 Master Bedroom Xbox Series X, Power: OFF
[03/01/2024, 17:21:55] [homebridge-xbox-tv] Device: 10.0.1.158 Master Bedroom Xbox Series X, Input: Screensaver, Reference: Xbox.IdleScreen_8wekyb3d8bbwe!Xbox.IdleScreen.Application, Product Id: Screensaver
[03/01/2024, 17:21:55] [homebridge-xbox-tv] Device: 10.0.1.158 Master Bedroom Xbox Series X, Current Media: STOP
[03/01/2024, 17:21:55] [homebridge-xbox-tv] Device: 10.0.1.158 Master Bedroom Xbox Series X, Target Media: STOP
[03/01/2024, 17:21:55] [homebridge-xbox-tv] Device: 10.0.1.158 Master Bedroom Xbox Series X, Mute: ON
[03/01/2024, 17:21:55] [homebridge-xbox-tv] Device: 10.0.1.158 Master Bedroom Xbox Series X, Volume: 0
[03/01/2024, 17:21:59] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[03/01/2024, 17:21:59] [homebridge-xbox-tv] Child bridge process ended
[03/01/2024, 17:21:59] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[03/01/2024, 17:22:06] [homebridge-xbox-tv] Restarting Process...
[03/01/2024, 17:22:07] [homebridge-xbox-tv] Launched child bridge with PID 285623
[03/01/2024, 17:22:07] Registering platform 'homebridge-xbox-tv.XboxTv'
[03/01/2024, 17:22:07] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.5 child bridge successfully
[03/01/2024, 17:22:07] Loaded 0 cached accessories from cachedAccessories.0ECF27A6D260.
[03/01/2024, 17:22:08] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 35233.
[03/01/2024, 17:22:15] Master Bedroom Xbox Series X 0EDB is running on port 43803.
[03/01/2024, 17:22:15] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[03/01/2024, 17:22:20] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[03/01/2024, 17:22:20] [homebridge-xbox-tv] Child bridge process ended

**Comment by chris4prez** [comment]
Export of my config:


    "devices": [
        {
            "name": "Living Room Xbox Series X",
            "host": "10.0.1.132",
            "xboxLiveId": "REMOVED",
            "webApiControl": true,
            "getInputsFromDevice": true,
            "filterGames": true,
            "filterApps": true,
            "filterSystemApps": true,
            "filterDlc": true,
            "inputsDisplayOrder": 1,
            "buttons": [
                {
                    "namePrefix": false
                }
            ],
            "sensorPower": false,
            "sensorInput": false,
            "sensorScreenSaver": false,
            "sensorInputs": [
                {
                    "namePrefix": false
                }
            ],
            "webApiPowerOnOff": true,
            "webApiRcControl": false,
            "webApiVolumeControl": false,
            "webApiToken": "REMOVED",
            "webApiClientId": "REMOVED",
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "infoButtonCommand": "nexus",
            "volumeControl": -1,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        },
        {
            "name": "Master Bedroom Xbox Series X",
            "host": "10.0.1.158",
            "xboxLiveId": "REMOVED",
            "webApiControl": false,
            "getInputsFromDevice": false,
            "filterGames": true,
            "filterApps": true,
            "filterSystemApps": true,
            "filterDlc": true,
            "inputsDisplayOrder": 1,
            "buttons": [
                {
                    "namePrefix": false
                }
            ],
            "sensorPower": false,
            "sensorInput": false,
            "sensorScreenSaver": false,
            "sensorInputs": [
                {
                    "namePrefix": false
                }
            ],
            "webApiPowerOnOff": false,
            "webApiRcControl": false,
            "webApiVolumeControl": false,
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "_bridge": {
        "username": "0E:CF:27:A6:D2:60",
        "port": 35233
    },
    "platform": "XboxTv"
}

**Comment by grzegorz914** [comment]
Every Xbox need to be authorized with authorization manager and need own token. 
Try to clear token first then start authorization manager again. If error occurs please post the debug log.

**Comment by chris4prez** [comment]
First xbox fully configured and working fine. 

How I attempt to add second xbox:

Launch plugin config
Select Clear WebAPI Token
Changed Hostname to new IP
Clicked Start Authorization

Receive following URL instead of the one with new WebAPI Token: http://localhost:8888/auth/callback?error=unauthorized_client&error_description=The%20client%20does%20not%20have%20a%20secret%20configured.%20If%20you%20are%20the%20client%20application%20developer%2c%20configure%20a%20secret%20through%20the%20application%20management%20site%20at%20https://go.microsoft.com/fwlink/%3flinkid%3d2083908.


attached debug log.
[homebridge-xbox-tv.log.txt](https://github.com/grzegorz914/homebridge-xbox-tv/files/13854621/homebridge-xbox-tv.log.txt)

**Comment by grzegorz914** [comment]
You can not replace first device, just add new one
![IMG_0930](https://github.com/grzegorz914/homebridge-xbox-tv/assets/28867813/a8ad0135-cfd3-4fc2-856a-64607ace5b4b)

**Comment by chris4prez** [comment]
Added new one. After first restart of the service, see the following in the logs:

[1/7/2024, 2:23:42 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 2:23:42 PM] [homebridge-xbox-tv] Process Ended. Code: 143, Signal: null
[1/7/2024, 2:23:49 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 2:23:50 PM] [homebridge-xbox-tv] Launched child bridge with PID 66845
[1/7/2024, 2:23:50 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
[1/7/2024, 2:23:50 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 2:23:50 PM] Loaded 0 cached accessories from cachedAccessories.0E903A0ADE61.
[1/7/2024, 2:23:50 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 49376.
[1/7/2024, 2:23:58 PM] Master Bedroom Xbox Series X 0EDB is running on port 41409.
[1/7/2024, 2:23:58 PM] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[1/7/2024, 2:24:03 PM] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/7/2024, 2:24:03 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 2:24:03 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 2:24:10 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 2:24:11 PM] [homebridge-xbox-tv] Launched child bridge with PID 67151
[1/7/2024, 2:24:11 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
[1/7/2024, 2:24:12 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 2:24:12 PM] Loaded 0 cached accessories from cachedAccessories.0E903A0ADE61.
[1/7/2024, 2:24:12 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 49376.
[1/7/2024, 2:24:19 PM] Master Bedroom Xbox Series X 0EDB is running on port 36789.
[1/7/2024, 2:24:19 PM] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[1/7/2024, 2:24:24 PM] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/7/2024, 2:24:24 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 2:24:24 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 2:24:31 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 2:24:32 PM] [homebridge-xbox-tv] Launched child bridge with PID 67370
[1/7/2024, 2:24:33 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
[1/7/2024, 2:24:33 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 2:24:33 PM] Loaded 0 cached accessories from cachedAccessories.0E903A0ADE61.
[1/7/2024, 2:24:33 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 49376.
[1/7/2024, 2:24:40 PM] Master Bedroom Xbox Series X 0EDB is running on port 42225.
[1/7/2024, 2:24:40 PM] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[1/7/2024, 2:24:45 PM] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/7/2024, 2:24:45 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 2:24:45 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 2:24:52 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 2:24:53 PM] [homebridge-xbox-tv] Launched child bridge with PID 67407
[1/7/2024, 2:24:54 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
[1/7/2024, 2:24:54 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 2:24:54 PM] Loaded 0 cached accessories from cachedAccessories.0E903A0ADE61.
[1/7/2024, 2:24:54 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 49376.
[1/7/2024, 2:24:54 PM] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, No oauth token found. Use authorization manager first.
[1/7/2024, 2:25:02 PM] Master Bedroom Xbox Series X 0EDB is running on port 42049.
[1/7/2024, 2:25:02 PM] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[1/7/2024, 2:25:07 PM] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/7/2024, 2:25:07 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 2:25:07 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 2:25:14 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 2:25:15 PM] [homebridge-xbox-tv] Launched child bridge with PID 67435
[1/7/2024, 2:25:15 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
[1/7/2024, 2:25:15 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 2:25:15 PM] Loaded 0 cached accessories from cachedAccessories.0E903A0ADE61.
[1/7/2024, 2:25:15 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 49376.
[1/7/2024, 2:25:15 PM] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, No oauth token found. Use authorization manager first.
[1/7/2024, 2:25:23 PM] Master Bedroom Xbox Series X 0EDB is running on port 38955.
[1/7/2024, 2:25:23 PM] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[1/7/2024, 2:25:28 PM] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/7/2024, 2:25:28 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 2:25:28 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 2:25:35 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 2:25:36 PM] [homebridge-xbox-tv] Launched child bridge with PID 67555
[1/7/2024, 2:25:37 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 2:25:37 PM] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, No oauth token found. Use authorization manager first.
[1/7/2024, 2:25:49 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 2:25:49 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 2:25:56 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 2:25:57 PM] [homebridge-xbox-tv] Launched child bridge with PID 67580
[1/7/2024, 2:25:58 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 2:25:58 PM] [homebridge-xbox-tv] Device: 10.0.1.132 Living Room Xbox Series X, No oauth token found. Use authorization manager first.
[1/7/2024, 2:26:10 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 2:26:10 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null

When I then select the second xbox and try to do the token get same url instead of webapi token
http://localhost:8888/auth/callback?error=unauthorized_client&error_description=The%20client%20does%20not%20have%20a%20secret%20configured.%20If%20you%20are%20the%20client%20application%20developer%2c%20configure%20a%20secret%20through%20the%20application%20management%20site%20at%20https://go.microsoft.com/fwlink/%3flinkid%3d2083908.

**Comment by grzegorz914** [comment]
Are you using your own `clientId`? if yes check your azure account. The error is about missing `secret` for `clientId`

**Comment by chris4prez** [comment]
Yes, using my own clientId. I should be using same one for both xboxes, correct?

Regarding the second I can't define it in the UI until after the authorization of the second xbox or should I manually define it in the config file?

**Comment by grzegorz914** [comment]
Client id need to be added in config before start authorization.

**Comment by chris4prez** [comment]
Still getting same error on trying to get second auth. Below is my config.

{
    "devices": [
        {
            "name": "Living Room Xbox Series X",
            "host": "10.0.1.132",
            "xboxLiveId": "REMOVED",
            "webApiControl": false,
            "getInputsFromDevice": true,
            "filterGames": true,
            "filterApps": true,
            "filterSystemApps": true,
            "filterDlc": true,
            "inputsDisplayOrder": 1,
            "sensorPower": false,
            "sensorInput": false,
            "sensorScreenSaver": false,
            "webApiPowerOnOff": true,
            "webApiRcControl": false,
            "webApiVolumeControl": false,
            "webApiToken": "",
            "webApiClientId": "DEFINEDANDREMOVED",
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "infoButtonCommand": "nexus",
            "volumeControl": -1,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        },
        {
            "name": "Master Bedroom Xbox Series X",
            "host": "10.0.1.158",
            "xboxLiveId": "REMOVED",
            "webApiControl": true,
            "getInputsFromDevice": true,
            "filterGames": true,
            "filterApps": true,
            "filterSystemApps": true,
            "filterDlc": true,
            "inputsDisplayOrder": 1,
            "sensorPower": false,
            "sensorInput": false,
            "sensorScreenSaver": false,
            "webApiPowerOnOff": true,
            "webApiRcControl": false,
            "webApiVolumeControl": false,
            "webApiClientId": "DEFINEDANDREMOVED",
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "infoButtonCommand": "nexus",
            "volumeControl": -1,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "_bridge": {
        "username": "0E:93:53:1A:16:EA",
        "port": 43729
    },
    "platform": "XboxTv"
}

**Comment by grzegorz914** [comment]
You have something wrong on Azure AD configured, the error took `unauthorized_client`, `the client don’t have secret configured`, so check your azure AD settings.

**Comment by chris4prez** [comment]
Why would it work for the first xbox then but not the second? Would I not see the error on the first one too?

**Comment by grzegorz914** [comment]
I don’t know, try to authorize without client id, leave this field empty

**Comment by chris4prez** [comment]
okay so was finally able to get both to auth. I had to make sure I did not define my clientID on the first xbox. The moment I defined it on the first the second would not auth.

I'm now getting the following error in the logs. You want me to start another thread for this issue?

[1/7/2024, 4:15:12 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 4:15:13 PM] [homebridge-xbox-tv] Launched child bridge with PID 92671
[1/7/2024, 4:15:14 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
[1/7/2024, 4:15:14 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 4:15:14 PM] Loaded 0 cached accessories from cachedAccessories.0E01E3143791.
[1/7/2024, 4:15:14 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 40409.
[1/7/2024, 4:15:21 PM] Master Bedroom Xbox Series X 0EDB is running on port 44043.
[1/7/2024, 4:15:21 PM] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[1/7/2024, 4:15:26 PM] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/7/2024, 4:15:26 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 4:15:26 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 4:15:33 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 4:15:34 PM] [homebridge-xbox-tv] Launched child bridge with PID 92961
[1/7/2024, 4:15:35 PM] Registering platform 'homebridge-xbox-tv.XboxTv'
[1/7/2024, 4:15:35 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 4:15:35 PM] Loaded 0 cached accessories from cachedAccessories.0E01E3143791.
[1/7/2024, 4:15:35 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-xbox-tv) is running on port 40409.
[1/7/2024, 4:15:43 PM] Master Bedroom Xbox Series X 0EDB is running on port 34915.
[1/7/2024, 4:15:43 PM] Please add [Master Bedroom Xbox Series X 0EDB] manually in Home app. Setup Code: 562-07-087
[1/7/2024, 4:15:48 PM] Parent process did not respond to port allocation request within 5 seconds - assigning random port.
Error: Accessory Living Room Xbox Series X experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:419:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[1/7/2024, 4:15:48 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 4:15:48 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 4:15:55 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 4:15:56 PM] [homebridge-xbox-tv] Launched child bridge with PID 93142
[1/7/2024, 4:15:56 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully
[1/7/2024, 4:16:09 PM] [homebridge-xbox-tv] Child bridge process ended
[1/7/2024, 4:16:09 PM] [homebridge-xbox-tv] Process Ended. Code: 1, Signal: null
[1/7/2024, 4:16:16 PM] [homebridge-xbox-tv] Restarting Process...
[1/7/2024, 4:16:17 PM] [homebridge-xbox-tv] Launched child bridge with PID 93168
[1/7/2024, 4:16:17 PM] [homebridge-xbox-tv] Loaded homebridge-xbox-tv v2.12.19 child bridge successfully



Config

    "devices": [
        {
            "name": "Living Room Xbox Series X",
            "host": "10.0.1.158",
            "xboxLiveId": "liveremoved",
            "webApiControl": true,
            "getInputsFromDevice": true,
            "filterGames": true,
            "filterApps": true,
            "filterSystemApps": true,
            "filterDlc": true,
            "inputsDisplayOrder": 1,
            "sensorPower": false,
            "sensorInput": false,
            "sensorScreenSaver": false,
            "webApiPowerOnOff": true,
            "webApiRcControl": false,
            "webApiVolumeControl": false,
            "webApiToken": "firsttokenremoved",
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "infoButtonCommand": "nexus",
            "volumeControl": -1,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        },
        {
            "name": "Master Bedroom Xbox Series X",
            "host": "10.0.1.158",
            "xboxLiveId": "liveremoved",
            "webApiControl": true,
            "getInputsFromDevice": true,
            "filterGames": true,
            "filterApps": true,
            "filterSystemApps": true,
            "filterDlc": true,
            "inputsDisplayOrder": 1,
            "sensorPower": false,
            "sensorInput": false,
            "sensorScreenSaver": false,
            "webApiPowerOnOff": true,
            "webApiRcControl": false,
            "webApiVolumeControl": false,
            "webApiToken": "secondtokenremoved",
            "enableDebugMode": false,
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "infoButtonCommand": "nexus",
            "volumeControl": -1,
            "enableRestFul": false,
            "restFulDebug": false,
            "enableMqtt": false,
            "mqttDebug": false,
            "mqttAuth": false
        }
    ],
    "_bridge": {
        "username": "0E:01:E3:14:37:91",
        "port": 40409
    },
    "platform": "XboxTv"
}

**Comment by grzegorz914** [comment]
Try to change the port of bridge

**Comment by chris4prez** [comment]
checked for open ports and changed, still receiving same error which constantly causes the plugin to crash and restart

**Comment by grzegorz914** [comment]
Disable and enable child bridge, remove HB cache, restart whole HB

**Comment by grzegorz914** [comment]
Close, because no response from user.
