### ISSUE TITLE
ReferenceError: powerState is not defined

### ISSUE THREAD

**Issue by brandonjjon** [grzegorz914/homebridge-xbox-tv#29]
Homebridge stuck in a reboot loop after installing this plugin. All configured correctly including xbox instant on, IP address and xboxliveid. This is a stock install of the [Homebridge Raspberry Pi Image](https://github.com/homebridge/homebridge-raspbian-image) with only two other plugins installed. Any help appreciated.

```
[5/15/2020, 17:24:27] ReferenceError: powerState is not defined
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:312:29)
    at EventEmitter.emit (events.js:322:22)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
    at EventEmitter.emit (events.js:310:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage (dgram.js:924:8)
[5/15/2020, 17:24:27] Got SIGTERM, shutting down Homebridge...
[5/15/2020, 17:24:32] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
```

**Comment by grzegorz914** [comment]
fixed
