### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by MingChops** [grzegorz914/homebridge-xbox-tv#60]
I believe this error is related to this plugin as it has only just happened from installing it and the error as you can see is nested within the XboxTV startup logging.

[12/5/2020, 2:25:29 AM] [XboxTv] Device: 192.168.1.17 Xbox One S, state: Online.
[12/5/2020, 2:25:29 AM] [XboxTv] -------- Xbox One S --------
[12/5/2020, 2:25:29 AM] [XboxTv] Manufacturer: Microsoft
[12/5/2020, 2:25:29 AM] [XboxTv] Model: Model Name
[12/5/2020, 2:25:29 AM] [XboxTv] Serialnr: Serial Number
[12/5/2020, 2:25:29 AM] [XboxTv] Firmware: Firmware Revision
[12/5/2020, 2:25:29 AM] [XboxTv] ----------------------------------
**(node:95396) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)**
[12/5/2020, 2:26:03 AM] [XboxTv] Device: 192.168.1.17 Xbox One S, get current App successful: Dashboard Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application
[12/5/2020, 2:26:03 AM] [XboxTv] Device: 192.168.1.17 Xbox One S, get current Power state successful, state: ON

Versions in use:
XboxTV (1.3.0)
Homebridge (v6.14.8)
Homebridge UI (v4.35.0)
MacOS (Catalina 10.15.7)

**Comment by benjaminLevinson** [comment]
Looks like the source of the issue is [this line](https://github.com/grzegorz914/homebridge-xbox-tv/blob/abf6a93a6ba1c0e7b77d7f9b46b82342f6bcdcc2/index.js#L424). [According to StackOverflow](https://stackoverflow.com/a/31443386), this issue can happen when a listener gets added within a loop. updateDeviveState() is being called in a loop [here](https://github.com/grzegorz914/homebridge-xbox-tv/blob/abf6a93a6ba1c0e7b77d7f9b46b82342f6bcdcc2/index.js#L134). So I think the solution is just to move this listener out of the device state refresh loop.

**Comment by benjaminLevinson** [comment]
I'm getting a crash that looks related to this. It happens after using the Control Center remote to navigate, after around 30+ inputs:
```
[12/8/2020, 9:40:19 PM] [XboxTv] Device: [IP] Xbox One, setRemoteKey successful,  command: right
[12/8/2020, 9:40:20 PM] [XboxTv] Device: [IP] Xbox One, setRemoteKey successful,  command: right
[12/8/2020, 9:40:21 PM] TypeError: me.xbox.getManager(...).sendCommand is not a function
    at xboxTvDevice.setRemoteKey (/homebridge/node_modules/homebridge-xbox-tv/index.js:673:29)
    at RemoteKey.emit (events.js:315:20)
    at RemoteKey.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at RemoteKey.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1461:24
    at Array.forEach (<anonymous>)
    at Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1303:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
```

**Comment by DavideVito** [comment]
same here

**Comment by grzegorz914** [comment]
Please try latest beta and get feedback.

**Comment by grzegorz914** [comment]
This is already fixed.
