### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by isaacpevy** [grzegorz914/homebridge-xbox-tv#73]
Hi there

I’m getting the below error. Is there anything I’m doing wrong? I can add it and use it for a moment but it very quickly gets into an endless loop where it reboots homebridge. Below is the error. I’ve also copied my config.

Thanks so much for your help!

`TypeError: Cannot read property '0' of undefined
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:270:38)
    at EventEmitter.emit (events.js:327:22)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:119:27)
    at EventEmitter.emit (events.js:315:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:270:38)
    at EventEmitter.emit (events.js:327:22)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:119:27)
    at EventEmitter.emit (events.js:315:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8) `

Config (I’ve blanked out the personal info):

`{
    "devices": [
        {
            "name": "XBOX",
            "host": "192.168.1.xxx",
            "xboxliveid": "F4XXXXXXXXXX",
            "refreshInterval": 5,
            "disableLogInfo": false,
            "volumeControl": 0,
            "switchInfoMenu": false,
            "manufacturer": "Microsoft",
            "modelName": "XBOX",
            "serialNumber": "XXXXXXX",
            "firmwareRevision": "XXXXX"
        }
    ],
    "platform": "XboxTv"
} `

**Comment by rmccracken397** [comment]
+1

**Comment by Baches** [comment]
+1

**Comment by ixy055** [comment]
+1

[15/03/2021, 4:53:04 pm] [XboxTv] Device: 192.168.0.116 xbox, state: Online.
[15/03/2021, 4:53:04 pm] [XboxTv] -------- xbox --------
[15/03/2021, 4:53:04 pm] [XboxTv] Manufacturer: Microsoft
[15/03/2021, 4:53:04 pm] [XboxTv] Model: Model Name
[15/03/2021, 4:53:04 pm] [XboxTv] Serialnr: Serial Number
[15/03/2021, 4:53:04 pm] [XboxTv] Firmware: Firmware Revision
[15/03/2021, 4:53:04 pm] [XboxTv] ----------------------------------
[15/03/2021, 4:53:26 pm] TypeError: Cannot read property '12' of undefined
    at EventEmitter.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-xbox-tv\index.js:270:38)
    at EventEmitter.emit (events.js:327:22)
    at EventEmitter.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-xbox-tv\node_modules\xbox-smartglass-core-node\src\events.js:119:27)
    at EventEmitter.emit (events.js:315:20)
    at Object.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-xbox-tv\node_modules\xbox-smartglass-core-node\src\smartglass.js:324:30)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
