### ISSUE TITLE
Homebridge on Synology DS with Bug by using this plugin

### ISSUE THREAD

**Issue by tommy536** [grzegorz914/homebridge-xbox-tv#85]
Hello, 

i have successfully installed and connected this plugin to a live account. Everything seems to work fine but homebridge gave me a failure message wich turns HB in a reboot circle.

5/16/2021, 8:55:09 PM] TypeError: Cannot read property '0' of undefined
    at EventEmitter.<anonymous> (/homebridge/node_modules/homebridge-xbox-tv/index.js:389:61)
    at EventEmitter.emit (events.js:388:22)
    at EventEmitter.<anonymous> (/homebridge/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:119:27)
    at EventEmitter.emit (events.js:376:20)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
    at Socket.emit (events.js:376:20)
    at UDP.onMessage (dgram.js:934:8)
[5/16/2021, 8:55:09 PM] Got SIGTERM, shutting down Homebridge...

What can i do here?

By the way, thanks for this great plugin!

**Comment by grzegorz914** [comment]
try 1.5.37-beta.0
