### ISSUE TITLE
Homebridge "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by anttesoriero** [grzegorz914/homebridge-xbox-tv#86]
When I try to turn on my Xbox One using homekit, my homebridge log shows me this error below. It was working earlier today but for some reason stopped. I have not changed anything with the plugin or the homebridge. No new plugins.

```
[XboxTv] Device: <HIDDEN_IP> <HIDDEN_NAME>, set power ON, error: TypeError: Cannot read property 'length' of undefined
    at Object.writeSGString (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/packet/structure.js:24:45)
    at Object.pack (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/packet/simple.js:45:45)
    at Object.pack (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/packet/simple.js:186:42)
    at Object.pack (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/packet/packer.js:46:30)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:97:47)
    at new Promise (<anonymous>)
    at Object.powerOn (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:86:20)
    at Active.setHandler (/usr/lib/node_modules/homebridge-xbox-tv/index.js:542:16)
    at Active.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:42)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
```

Any clue of what could be wrong or how I can fix this?

Running on fully updated rpi 4 with newest plugin verison.

**Comment by asyba** [comment]
same issue, it works while turning off, but turn on it show the same error.

**Comment by ArtemKiyashko** [comment]
have the same

**Comment by grzegorz914** [comment]
Is this issue exists?

**Comment by grzegorz914** [comment]
I close this as solved, if not free to open it again.
