### ISSUE TITLE
ReferenceError: error is not defined

### ISSUE THREAD

**Issue by TechnikMax** [grzegorz914/homebridge-xbox-tv#9]
Hello, 
when I activate the plugin, this error is prompted and the homebridge is restarting. After restarting, this error comes again > Infinite loop.

```
[4/6/2020, 8:44:13 PM] ReferenceError: error is not defined
    at Object.<anonymous> (/homebridge/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:188:40)
    at EventEmitter.emit (events.js:323:22)
    at EventEmitter.<anonymous> (/homebridge/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
    at EventEmitter.emit (events.js:311:20)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:264:30)
    at Socket.emit (events.js:311:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
[4/6/2020, 8:44:13 PM] Got SIGTERM, shutting down Homebridge...
[4/6/2020, 8:44:18 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/6/2020, 8:44:23 PM] [HB Supervisor] Restarting Homebridge...
```

**Comment by grzegorz914** [comment]
Please enable debug mod -D and post complete log.

**Comment by TechnikMax** [comment]
It seems that the plugin is not creating the ‘appsFile’, the ‘xboxTV’ folder exists but is empty. When I remove the apps property in the settings no error occurs.

```
Setup Payload:
X-HM://0*********B
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-**-154 │     
    └────────────┘     
                       
[4/7/2020, 8:42:32 AM] Homebridge is running on port 51831.
[4/7/2020, 8:42:32 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/7/2020, 8:42:37 AM] [HB Supervisor] Restarting Homebridge...
[4/7/2020, 8:42:37 AM] [HB Supervisor] Starting Homebridge with extra flags: -P /homebridge/node_modules -D
[4/7/2020, 8:42:38 AM] [HB Supervisor] Started Homebridge with PID: 1271
[4/7/2020, 8:42:45 AM] Loaded config.json with 1 accessories and 1 platforms.
[4/7/2020, 8:42:46 AM] ---
[4/7/2020, 8:42:57 AM] Loaded plugin: homebridge-xbox-tv
[4/7/2020, 8:42:57 AM] Registering platform 'homebridge-xbox-tv.XboxTv'
[4/7/2020, 8:42:57 AM] ---
[4/7/2020, 8:42:57 AM] Loaded plugin: homebridge-config-ui-x
[4/7/2020, 8:42:57 AM] Registering platform 'homebridge-config-ui-x.config'
[4/7/2020, 8:42:57 AM] ---
[4/7/2020, 8:42:57 AM] [XboxTv] Initializing XboxTv platform...
[4/7/2020, 8:42:58 AM] [XboxTv] didFinishLaunching
[4/7/2020, 8:42:59 AM] [XboxTv] prepereTvService
[4/7/2020, 8:42:59 AM] [XboxTv] prepereTvSpeakerService
[4/7/2020, 8:42:59 AM] [XboxTv] prepareInputServices
[4/7/2020, 8:42:59 AM] [XboxTv] Device: 192.168.178.***, inputs file does not exist
[4/7/2020, 8:42:59 AM] TypeError: appReference.replace is not a function
    at /homebridge/node_modules/homebridge-xbox-tv/index.js:290:33
    at Array.forEach (<anonymous>)
    at xboxTvDevice.prepareInputServices (/homebridge/node_modules/homebridge-xbox-tv/index.js:268:13)
    at xboxTvDevice.prepareTvService (/homebridge/node_modules/homebridge-xbox-tv/index.js:224:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[4/7/2020, 8:42:59 AM] Got SIGTERM, shutting down Homebridge...

```

**Comment by grzegorz914** [comment]
If U use empty reference in Your config.json, please remove it and test again.
for example:
```
                        {
                            "name": "Game",
                            "reference": ""
                        },
```

**Comment by TechnikMax** [comment]
Thanks, now it’s working.
